### ISSUE TITLE
作业例子完成后，有个关于Players使用的疑惑

### ISSUE THREAD

**Issue by xusai2014** [maodouio/meteorcamp#2]
Origin code：
 players: function () {
      return **Players.find({}, { sort: { score: -1, name: 1 } });**
    },

My code:
 players: function () {
      return **Players.find({}, { sort: { score: -1, name: 1 } }).fetch();**
    },
Origin Code 中 payers 在Template中 {{#each players}}遍历这个数据对象，但是{{#if}}无法判断length或者是否为空，所以我就换了第二种方式就可以了这是Okay的，我对第一种使用的players 数据结构有疑问，或者说 我们在操作数据库数据时候有哪些需要注意的点。谢谢！

**Comment by tiansiyuan** [comment]
你的项目代码放到github上了吗？告诉我地址。那样看起来更清楚。

**Comment by limingth** [comment]
一般需要页面数据随着数据库的改变动态自动刷新的，**都不要用 fetch()**

**Comment by haizi-zh** [comment]
@limingth 老师说得很对，在这个场景下不推荐使用`fetch()`，那是一种_anti pattern_。

`find()`方法返回的是数据库的游标，通过迭代器的模式，Meteor可以很好地和游标配合工作。如果使用`fetch()`，相当于强行地将游标内容一次性读取出来，形成一个数组。在这种情况下，无论是效率，还是代码可读性，还是和Tracker等的配合方面，都有潜在的问题。
