### ISSUE TITLE
关于添加leaderboard的player的问题

### ISSUE THREAD

**Issue by LionelChen** [maodouio/meteorcamp#3]
老师同学们晚上好，

我试了试昨天李老师留下的练习，在添加player的时候遇到了问题。
下面的代码没有办法添加新的player，
经过调试我发现根本没有运行下面的js函数，google无果，请大家帮我看看，谢谢！

html:

<img width="328" alt="screen shot 2016-01-19 at 8 11 15 pm" src="https://cloud.githubusercontent.com/assets/7126987/12418207/d521b7d6-bee8-11e5-84be-ca16140179ac.png">
js:
Template.leaderboard.events({
    'click .add_player': function () {
      var player_name=document.getElementById("plyname").value;
      alert(player_name);
      Players.insert({"_id" : "gquNP63mJqTjar6","name" : this.player_name, "score" : 0});
    }
  });

**Comment by LionelChen** [comment]
repo地址:https://github.com/LionelChen/meteorleaderboard

**Comment by limingth** [comment]
@LionelChen 可以参考 https://github.com/klbjlabs/hero 的实现代码
