### ISSUE TITLE
对这种自动化开发有一些困惑

### ISSUE THREAD

**Issue by afayear** [maodouio/meteorcamp#5]
学过一点ruby on rails和meteor一样，都是几行命令可以生成一个简单的网页，好像就是在操作一些命令，其中发生了什么，就不知道，出了问题也很难排查，所以比较困惑，这种自动化的过程，虽然能很快生成一些网页实现一些简单功能，但是真需要自己定制一些东西的时候，就感觉无所下手。

**Comment by limingth** [comment]
同感，尤其是对于我们这些从汇编/C语言学出来的开发者，希望看到每一行代码背后的实现机理和完整逻辑。
但在Web开发框架下，这些都是美好的理想，现实的办法只能是存疑前行，并且相信有一天回过头这些都会搞明白的，呵呵 😄

**Comment by haizi-zh** [comment]
从学习的角度来说，我们希望每一个功能，都是通过自己的双手，自己的键盘来实现。从实际应用的角度来说，上面的作法其实效率非常低，而且不利于标准化。我个人的建议是这样的：
- 在学习时，当具有一定基础以后，一定要尝试着阅读源代码，知道这些命令背后大致是怎样的工作原理。
- 在开发时，放心大胆地使用你所谓的“自动化开发”的方式。

**Comment by afayear** [comment]
谢谢。
