### ISSUE TITLE
请教在mongoDB删除操作时的一个问题

### ISSUE THREAD

**Issue by ghost** [maodouio/meteorcamp#6]
如何删除第2个文档，而不影响第3，4个文档？
meteor:PRIMARY> db.co1.find({name: "liyang"})
{ "_id" : ObjectId("56a10fbe0a98da026f3b633a"), "name" : "liyang" }
{ "_id" : ObjectId("56a110700a98da026f3b633b"), "name" : "liyang", "age" : 28 }
{ "_id" : ObjectId("56a110a40a98da026f3b633c"), "name" : "liyang", "age" : 28, "count" : 1 }
{ "_id" : ObjectId("56a110a70a98da026f3b633d"), "name" : "liyang", "age" : 28, "count" : 2 }

**Comment by haizi-zh** [comment]
可以通过更加细致地设置查询条件来办到这一点：

```
db.co1.remove({name: "liyang", age: 28, count: null})
```

**Comment by limingth** [comment]
厉害！  我还准备回复 

```
db.co1.remove({"_id" : ObjectId("56a110700a98da026f3b633b")}) 
```

😄

**Comment by haizi-zh** [comment]
@limingth 李老师说得也是对的。事实上，使用主键`_id`来删除某一条记录，是更加安全的作法。如果可以方便地使用`_id`来引用某一条文档的话，推荐使用这种方式。不过有些时候，从业务逻辑语境来说，也许要想使用`_id`，或许会不太方便。那样的话，就是用我的做法吧。
